spring:
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_batch_fetch_size: 128
        id.new_generator_mappings: true
        show_sql: true
        use_sql_comments: true
        hbm2ddl.auto: update
        check_nullability: true
        query.in_clause_parameter_padding: true
    open-in-view: false
    show-sql: true

  data:
    redis:
      port: 36379
      repositories:
        enabled: false

coupon.datasource:
  writer:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:33306/coupon?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    maximumPoolSize: 10
  reader:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:33307/coupon?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    maximumPoolSize: 10

logging:
  level:
    coupon:
      config:
        RoutingDataSource: DEBUG
