version: '3'
services:
  mysql_writer:
    user: root
    build:
      context: ./writer
      dockerfile: Dockerfile
    ports:
      - 33306:3306
    networks:
      coupon_dock_net:
        ipv4_address: 172.20.0.10
    volumes:
      - ./data/writer:/var/lib/mysql
    container_name: mysql_writer
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coupon
      TZ: Asia/Seoul

  mysql_reader:
    user: root
    build:
      context: ./reader
      dockerfile: Dockerfile
    ports:
      - 33307:3306
    networks:
      coupon_dock_net:
        ipv4_address: 172.20.0.11
    volumes:
      - ./data/reader:/var/lib/mysql
    container_name: mysql_reader
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coupon
      TZ: Asia/Seoul
    depends_on:
      - mysql_writer

  redis:
    image: redis:7.0.12
    container_name: redis
    restart: always
    ports:
      - "36379:6379"
    networks:
      coupon_dock_net:
        ipv4_address: 172.20.0.20

networks:
  coupon_dock_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
